=== kriszkecodecool/xml/NE9JRL_1005/IK_orarend.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="tanitasiHet">
		<xs:complexType>
			<xs:sequence>
				<xs:element	name="orarend" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ora" type="xs:string"/>
							<xs:element name="targy" type="xs:unsignedShort"/>
							<xs:element name="idopont"/>
								<xs:sequence>
									<xs:element name="nap" type="xs:string"/>
									<xs:element name="tol" type="xs:unsignedShort"/>
									<xs:element name="ig" type="xs:unsignedShort"/>
								</xs:sequence>
							<xs:element name="helyszin" type="xs:string"/>
							<xs:element name="oktato" type="xs:string"/>
							<xs:element name="szak" type="xs:string" />
							</xs:sequence>
						<xs:attribute name="id" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== kriszkecodecool/xml/NE9JRL_1012/IK_orarend.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE xml>


<tanitasiHet xmlns:xs="http://www.w3.org/2001/XMLSchema" xs:noNamespaceSchemaLocation="http://www.example.com/SpaceWarGame IK_orarend.xsd">

	<orarend id = "Hétfő">
	
		<ora id = "webtech" típus = "elmélet">
		<targy>WEB technológiák</targy> 
			
		<idopont>
			<nap>Hétfő </nap>
			<tol> 12:00 </tol>
			<ig> 14:00 </ig>
		</idopont>
		
		<helyszin> XXX A1 305. terem </helyszin>
		<oktato> Agárdi Anita </oktato>
		<szak> Programtervező Informatikus </szak>
		</ora>
		
		<ora id = "MesInt" típus = "elmélet">
		<targy> Mesterséges Intelligencia </targy> 
		
		<idopont>
			<nap>  Hétfő </nap>
			<tol> 14:00 </tol>
			<ig> 17:00 </ig>
		</idopont>
		
		<helyszin> A1 magasfsz XXXII. előadó </helyszin>
		<oktato> Dr. Dudás László </oktato>
		<szak> Programtervező Informatikus </szak>
		</ora>
		
	</orarend>
	
	
	<orarend id ="Kedd">
	
		<ora id = "XML" típus = "elmélet">
		<targy>Adatkezelés XML-ben</targy> 
		
		<idopont>
			<nap> Kedd </nap>
			<tol> 12:00 </tol>
			<ig> 14:00 </ig>
		</idopont>
		
		<helyszin> A2 fsz. I. előadó  </helyszin>
		<oktato> Dr. Bednarik László </oktato>
		<szak> Programtervező Informatikus </szak>
		</ora>
		
		<ora id = "XML" típus = "gyakorlat">
		<targy>Adatkezelés XML-ben</targy> 
		
		<idopont>
			<nap> Kedd </nap>
			<tol> 14:00 </tol>
			<ig> 16:00 </ig>
		</idopont>
		
		<helyszin> Informatika épület 103. terem </helyszin>
		<oktato> Dr. Bednarik László </oktato>
		<szak> Programtervező Informatikus </szak>
		</ora>
		
		<ora id = "webtech" típus = "gyakorlat">
		<targy>WEB technológiák</targy> 
		
		<idopont>
			<nap> Kedd </nap>
			<tol> 16:00 </tol>
			<ig> 18:00 </ig>
		</idopont>
		
		<helyszin> Informatika épület 103. terem </helyszin>
		<oktato> Agárdi Anita </oktato>
		<szak> Programtervező Informatikus </szak>
		</ora>
		
	</orarend>
	
	
	
	
	<orarend id = "Szerda">
		<ora id = "MesInt" típus = "gyakorlat">
		<targy> Mesterséges Intelligencia</targy> 
		
		<idopont>
			<nap> Szerda </nap>
			<tol> 10:00 </tol>
			<ig> 11:00 </ig>
		</idopont>
		
		<helyszin> Informatika épület 15. terem </helyszin>
		<oktato> Dr. Dudás László </oktato>
		<szak> Programtervező Informatikus </szak>
		</ora>
		
		<ora id = "VállalatiInfó" típus = "elmélet">
		<targy> Vállalati információs rendszerek </targy> 
		
		<idopont>
			<nap> Szerda </nap>
			<tol> 16:00 </tol>
			<ig> 18:00 </ig>
		</idopont>
		
		<helyszin> Informatika épület 103. terem </helyszin>
		<oktato> Dr. Sasvári Péter </oktato>
		<szak> Programtervező Informatikus </szak>
		</ora>
		
		<ora id = "VállalatiInfó" típus = "gyakorlat">
		<targy> Vállalati információs rendszerek </targy> 
		
		<idopont>
			<nap> Szerda </nap>
			<tol> 18:00 </tol>
			<ig> 20:00 </ig>
		</idopont>
		
		<helyszin> Informatika épület 103. terem </helyszin>
		<oktato> Dr. Sasvári Péter </oktato>
		<szak> Programtervező Informatikus </szak>
		</ora>
		
	</orarend>

</tanitasiHet>
